### ISSUE TITLE
Tutorial broken with Dart 1.6.0 (DEV) at perf_api line 9

### ISSUE THREAD

**Issue by wstidolph** [angular/angular.dart.tutorial#128]
Current Tutorial master Chapter 1, run index.html in Dart Editor ver 1.6.0.dev_08_00 (DEV) or in IntelliJ IDEA using Dart SDK 1.6.0-dev.8.0, get this error in Dartium on Win 8.1 64 bit:

```
Internal error: 'package:perf_api/perf_api.dart': error: line 9 pos 29: expression is not a valid compile-time constant
final Counters counters = new Counters();
                              ^
```

(as of angular/angular.dart.tutorial@57af7fb)

**Comment by java4kids** [comment]
I've just downloaded the Dart + Editor (11.8.5) on Mac, and some of the code samples don't work. In particular, running the example piratebadge.html from 4-extractcomponent project gives me

Internal error: 'package:perf_api/perf_api.dart': error: line 9 pos 29: expression is not a valid compile-time constant
  final Counters counters = new Counters();

Tis would definitely give people bad impression of the Dart team.
